AWSTemplateFormatVersion: 2010-09-09
Resources:
    DependsOn:
      - TextractAsyncJobSubmitFunction
      - DocumentAnalysisLambdaInvokeS3Permission
    Condition: NewDocumentBucketCreation
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - '-'
        - - !Ref 'AWS::AccountId'
          - !Ref redvelvetstoragebucket
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt 
              - TextractAsyncJobSubmitFunction
              - Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: pdf
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt 
              - TextractAsyncJobSubmitFunction
              - Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: jpg
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt 
              - TextractAsyncJobSubmitFunction
              - Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: jpeg